"""add_display_name_to_packages_and_events

Revision ID: 3fa31540eff3
Revises: 8efd0868bab9
Create Date: 2026-08-10 22:44:30.206400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa31540eff3'
down_revision: Union[str, None] = '8efd0868bab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('display_name', sa.Text(), nullable=True))
    op.add_column('tracking_events', sa.Column('display_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracking_events', 'display_name')
    op.drop_column('packages', 'display_name')
    # ### end Alembic commands ###
